name: Publish to TestFlight
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - uses: actions/checkout@v2
      - name: Add TOKEN
        run: cd VideoSDKRTC_Example/API && rm Constants.swift && touch Constants.swift && echo "import Foundation; public let AUTH_URL = \"\"; public let AUTH_TOKEN = \"${{secrets.AUTH_TOKEN}}\";" >> Constants.swift && ls && cat Constants.swift
      - name: Install Pods
        run: pod install

      - name: Build IOS App
        uses: yukiarrr/ios-build-action@v1.5.0
        with:
          project-path: VideoSDKRTC_Example.xcodeproj
          p12-base64: ${{ secrets.P12_BASE64 }}
          mobileprovision-base64: |
            ${{ secrets.MOBILEPROVISION_BASE64 }}
          code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
          team-id: ${{ secrets.TEAM_ID }}
          certificate-password: ${{ secrets.CERTIFICATE_PASSWORD}}
          scheme: VideoSDKRTC_Example
          workspace-path: VideoSDKRTC_Example.xcworkspace # optional
          export-options: ExportOptions.plist

      - name: "Upload app to TestFlight"
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: "output.ipa"
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
